/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.Koneksi;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Gilang Brilians
 */
public class DaftarSiswaBaru extends javax.swing.JFrame {

    /**
     * Creates new form DaftarSiswaBaru
     */
    public DaftarSiswaBaru() {
        initComponents();
        
         //agar icon logo pada label sesuai dengan luas label
        ImageIcon Logo = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("logo_login.png")));
        Image logo = Logo.getImage();
        Image logo1 = logo.getScaledInstance(jLabel10.getWidth(), jLabel10.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(logo1);
        jLabel10.setIcon(i);
        
        //agar icon logo pada label sesuai dengan luas label
        ImageIcon Illustrasi = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("inputdata.jpg")));
        Image illustrasi = Illustrasi.getImage();
        Image illustrasi1 = illustrasi.getScaledInstance(jLabel9.getWidth(), jLabel9.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon x = new ImageIcon(illustrasi1);
        jLabel9.setIcon(x);
        
        //Button daftar jadi Transparant
        daftarbtn.setOpaque(false);
        daftarbtn.setContentAreaFilled(false);
        daftarbtn.setBorderPainted(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        agamacmb = new javax.swing.JComboBox<String>();
        jkrb = new javax.swing.JLabel();
        nisntxt = new javax.swing.JTextField();
        namatxt = new javax.swing.JTextField();
        tempattxt = new javax.swing.JTextField();
        tanggaltxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        daftarbtn = new javax.swing.JButton();
        JKcmb = new javax.swing.JComboBox<String>();
        jLabel6 = new javax.swing.JLabel();
        jrscmb = new javax.swing.JComboBox<String>();
        emiltxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Nunito Sans", 0, 11)); // NOI18N
        jLabel1.setText("NISN");

        jLabel2.setFont(new java.awt.Font("Nunito Sans", 0, 11)); // NOI18N
        jLabel2.setText("Nama Lengkap");

        jLabel3.setFont(new java.awt.Font("Nunito Sans", 0, 11)); // NOI18N
        jLabel3.setText("Tempat Lahir");

        jLabel4.setFont(new java.awt.Font("Nunito Sans", 0, 11)); // NOI18N
        jLabel4.setText("Tanggal Lahir");

        jLabel5.setFont(new java.awt.Font("Nunito Sans", 0, 11)); // NOI18N
        jLabel5.setText("Agama");

        agamacmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Islam", "Hindu", "Kristen", "Katolik", "Buddha" }));

        jkrb.setFont(new java.awt.Font("Nunito Sans", 0, 11)); // NOI18N
        jkrb.setText("Jenis Kelamin");

        nisntxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(220, 5, 100)));
        nisntxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        namatxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(220, 5, 100)));

        tempattxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(220, 5, 100)));

        tanggaltxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(220, 5, 100)));

        jLabel8.setFont(new java.awt.Font("Nunito Sans", 1, 14)); // NOI18N
        jLabel8.setText("Lengkapi Data Diri Kamu");

        daftarbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/submit.png"))); // NOI18N
        daftarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                daftarbtnActionPerformed(evt);
            }
        });

        JKcmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laki-laki", "Perempuan" }));

        jLabel6.setFont(new java.awt.Font("Nunito Sans", 0, 11)); // NOI18N
        jLabel6.setText("Jurusan Pilihan");

        jrscmb.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Rekayasa Perengkat Lunak", "Teknik Komputer dan Jaringan", "Multimedia" }));
        jrscmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrscmbActionPerformed(evt);
            }
        });

        emiltxt.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(220, 5, 100)));

        jLabel7.setFont(new java.awt.Font("Nunito Sans", 0, 11)); // NOI18N
        jLabel7.setText("Email");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(emiltxt)
                    .addComponent(tempattxt)
                    .addComponent(jLabel7)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jrscmb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jkrb, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JKcmb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(agamacmb, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(daftarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(tanggaltxt)
                    .addComponent(namatxt)
                    .addComponent(nisntxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(6, 6, 6)
                        .addComponent(nisntxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel2)
                        .addGap(8, 8, 8)
                        .addComponent(namatxt, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel3)
                        .addGap(6, 6, 6)
                        .addComponent(tempattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel4)
                        .addGap(6, 6, 6)
                        .addComponent(tanggaltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addComponent(jLabel7)
                        .addGap(6, 6, 6)
                        .addComponent(emiltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)
                        .addComponent(jkrb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JKcmb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addComponent(agamacmb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jrscmb, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(daftarbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void add(){
        if (nisntxt.getText().isEmpty()|| namatxt.getText().isEmpty()||tanggaltxt.getText().isEmpty()||tempattxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this,"Isi semua data!","Warning",JOptionPane.WARNING_MESSAGE);
        }else{
            String nisn, nama, jenisK, tanggal,tempat, email, agama,jurusanP;
            nama = namatxt.getText();
            nisn = nisntxt.getText();
            tempat = tempattxt.getText();
            tanggal = tanggaltxt.getText();
            email = emiltxt.getText();
            jenisK = JKcmb.getSelectedItem().toString();
            agama = agamacmb.getSelectedItem().toString();
            jurusanP = jrscmb.getSelectedItem().toString();
            String sql = "INSERT INTO datapendaftar(Nisn,nama,tempatLahir,tanggalLahir,Email,Agama,JenisKelamin,JurusanPilihan) VALUES(?,?,?,?,?,?,?,?)";
            try{
                java.sql.Connection conn = Koneksi.configDB();
                PreparedStatement st = conn.prepareStatement(sql);
                st.setString(1,nisn);
                st.setString(2,nama);
                st.setString(3,tempat);
                st.setString(4,tanggal);
                st.setString(5,email);
                st.setString(6,agama);
                st.setString(7,jenisK);
                st.setString(8,jurusanP);
                
                st.executeUpdate();
                JOptionPane.showMessageDialog(this,"Sukses Mendaftar!","Success",JOptionPane.PLAIN_MESSAGE);
                LandingPage lp = new LandingPage();
                lp.setVisible(true);
                this.dispose();
            }catch(SQLException e){
                JOptionPane.showMessageDialog(this,"Gagal Mendaftar!    ("+e+")","Error",JOptionPane.ERROR_MESSAGE);
            }
        }
    }
    private void jrscmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrscmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrscmbActionPerformed

    private void daftarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_daftarbtnActionPerformed
        add();
    }//GEN-LAST:event_daftarbtnActionPerformed
     
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DaftarSiswaBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DaftarSiswaBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DaftarSiswaBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DaftarSiswaBaru.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DaftarSiswaBaru().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JKcmb;
    private javax.swing.JComboBox<String> agamacmb;
    private javax.swing.JButton daftarbtn;
    private javax.swing.JTextField emiltxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jkrb;
    private javax.swing.JComboBox<String> jrscmb;
    private javax.swing.JTextField namatxt;
    private javax.swing.JTextField nisntxt;
    private javax.swing.JTextField tanggaltxt;
    private javax.swing.JTextField tempattxt;
    // End of variables declaration//GEN-END:variables
}
